services:
  # BACKEND
  backend: # The name of the service, can be anything
    image: todo-backend-dev # Declares which image to use
    build: # Declares where to build if image is not found
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/the_database
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data

  #FRONTEND
  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: todo-front-dev # This will name the container hello-front-dev
  #REVERESE PROXY
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
