# events is required, but defaults are ok
events { }

# A http server, listening at port 80
http {
  server {
    listen 80;

    # Requests starting with root (/) are handled
    location / {
      # Requests are directed to the frontend nginx container
      proxy_pass http://app:80/;
    }
    location /api/ {
      proxy_pass http://backend:3000/;
    }
  }
}